name: Backend CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Show workspace
        run: |
          node -v
          npm -v
          ls -la

      - name: Lint
        run: npm run lint

      # 서버를 실제로 띄우지 않고 구문/모듈 로딩만 확인
      - name: Smoke test (syntax & require)
        run: |
          node -e "require('./index.js'); console.log('OK: index.js required')"
